### PR TITLE
permissions shared across roles fix #3

### LINKED ISSUE #3: permissions shared across roles
Hi @ourway ,
Nice package. I was trying to write some tests and noticed that there's like a **one to one** relation between Roles and Permissions. It seems intentional ( according to the code ). Wouldn't be great to have permissions shared across roles ?
If so, i would be glad to contribute by submitting a patch

### PR DESCRIPTION
**Pull request by josuebrunel**
Hi @ourway ,
Thanks again for the lib. To summarize this patch allow roles to have multiple permissions.

### CODE REVIEW

**Comment by josuebrunel** [comment]
Sorry i didn't update the .travis.yaml to use pyttest. I forgot to wirte a migration script for AuthMembership collections. Anyway, i keep you posted

**Comment by josuebrunel** [comment]
test with py26 are failing because of a  dependency ( mongomock, a simple dict comprehension )

**Comment by josuebrunel** [comment]
Hi @ourway, just noticed that you merged my pull request. However, the migration script is still to be done. I will check this out ASAP. 
My tests through [travis](https://travis-ci.org/josuebrunel/auth)

**Comment by ourway** [comment]
Thanks. I am waiting for it.

**Pull request merged**
